version: "3.3"
services:
  sqlserver:
     build:
       context: ./
       dockerfile: ./Docker/Sql.Dockerfile
     ports:
       - "1433:1433"
     networks:
        - development_network

  integration_tests:
     build:
       context: ./
       dockerfile: ./Docker/Dev.Dockerfile
     depends_on:
       - sqlserver
     ports:
        - "5000:5000"
     networks:
        - development_network

networks:
    development_network: